### ISSUE TITLE
Update to proxy-agent 4.0.1 to address netmask vulnerability

### ISSUE THREAD

**Issue by traeblain** [snoguchi/node-fetch-with-proxy#9]
Netmask has a vulnerability and this needs to be updated to proxy-agent 4.0.1 in order to address the issue.  Would that be doable?

**Comment by snoguchi** [comment]
@traeblain Thanks for reminding me! 
Updated proxy-agent in https://github.com/snoguchi/node-fetch-with-proxy/commit/26418e00180e8c5ca5bd1f5bea08011be973548a and published as [v0.1.4](https://www.npmjs.com/package/node-fetch-with-proxy/v/0.1.4).
